### PR TITLE
Added private sheet support, #57

### PR DESCRIPTION
**Pull request by sigilion**
This should work, although I have only been able to test with new style spreadsheets.

### CODE REVIEW

**Comment by manuel-jasso** [comment]
Hi @jsoma, I'd like to be able to read private sheets also, any plans to marge @sigilion's PR?

**Comment by eherrerosj** [comment]
why hasn't this PR been merged? seems like `authkey` is being parsed as a parameter but never used, am I right?

**Comment by dalbanhi** [comment]
Hi, wondering still about this pull request, would be awesome to have this integration and thanks @jsoma for Tabletop, has been great so far!

**Comment by jsoma** [comment]
I have no idea why I never merged this, especially since I (as mentioned) for some reason had `auth_key` already in there. Just added it in.

**Pull request closed without merging**
