### PR TITLE
Test if in browser environment to support browserify

### PR DESCRIPTION
**Pull request by timwis**
Fixes jsoma/tabletop#74 and jsoma/tabletop#76

Sorry about the whitespace diffs. Not sure how to ignore them in the commit.

### CODE REVIEW

**Comment by timwis** [comment]
Also note that to use this in browserify you have to use `var Tabletop = require('tabletop').Tabletop;`

**Comment by thomaswilburn** [comment]
Would love to have this added--we're using this for a web component at the Seattle Times and will currently have to manually install instead of using NPM for Tabletop.

**Comment by timwis** [comment]
@thomaswilburn FYI in the meantime I just use `npm install --save timwis/tabletop` -- you can do the same think (fork it, implement the changes, and npm install it) until the pull request is merged. Beats installing it manually.

**Comment by thomaswilburn** [comment]
Good point Tim, thanks!

**Comment by igierard** [comment]
Might I suggest adding a "browser" module relace to the package.json for the "request" module as seen in https://github.com/juxtinteractive/tabletop/tree/browserify-support . The "request" module has a lot of dependincies that are unneeded for this module on the client.

**Comment by thomaswilburn** [comment]
To be honest, it may make sense to load the dependencies in a way that Browserify doesn't see them (such as using a variable name for the require path, instead of a string) so that they don't get loaded at all in a client-side build. The same problem with `request` is also probably going to come up for the `mime` module.

**Comment by igierard** [comment]
@thomaswilburn yeah that would be a lot cleaner.

**Pull request closed without merging**
